# Notice MCP Server 配置文件
# 仅包含已实现的后端：macOS 和飞书

[server]
name = "Notice MCP Server"
version = "1.0.0"
port = 3000
debug = false

[logging]
level = "info"
file = "logs/notice-mcp.log"
enable_console = true

# MacOS系统通知配置
[backends.macos]
enabled = true
default_sound = "Glass"
default_subtitle = "来自 Notice MCP"
show_in_notification_center = true

# 飞书通知配置
[backends.feishu]
enabled = true
webhook_url = "https://open.feishu.cn/open-apis/bot/v2/hook/6480e218-0e67-4c40-91e6-379cdc95fb07"
# secret = "your-secret-key"  # 可选，用于验证消息来源

# Webhook通知配置（已注释）
# [backends.webhook]
# enabled = false
# default_url = "https://your-webhook-endpoint.com/notify"
# default_method = "POST"
# timeout = 5000

# 速率限制配置
[rate_limiting]
enabled = true
max_requests_per_minute = 60

# 每个后端的速率限制
[rate_limiting.backends]
macos = 60      # 每分钟最多60个系统通知
feishu = 30     # 每分钟最多30条飞书消息
# webhook = 30    # 每分钟最多30个webhook请求（已注释）