# Notice MCP Server 配置文件示例
# 复制此文件为 config.toml 并取消注释需要的配置项

# macOS 通知后端配置
# [macos]
# enabled=true

# 飞书通知后端配置
# [feishu]
# enabled=true
# 支持配置多个webhook URL，可同时发送到多个飞书群
# webhook = [
#     "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_WEBHOOK_TOKEN_HERE",
#     "https://open.feishu.cn/open-apis/bot/v2/hook/ANOTHER_WEBHOOK_TOKEN_HERE"
# ]