# Notice MCP Server 配置文件示例
# 基于实际使用的配置格式
#
# 使用说明：
# 1. 复制此文件为 config.toml
# 2. 根据需要修改配置参数
# 3. 填写您的实际飞书机器人配置信息
# 4. config.toml 文件已被 .gitignore 忽略，不会被提交到版本控制

# macOS 系统通知配置
[macos]
enabled = true

# 飞书通知配置
[feishu]
enabled = true
webhooks = [
    "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_WEBHOOK_TOKEN"
]

# 注意：
# - 将 YOUR_WEBHOOK_TOKEN 替换为您的实际飞书机器人 Webhook Token
# - 可以配置多个 webhook URL，系统会依次尝试发送
# - macOS 通知无需额外配置，启用即可使用