# Notice MCP Server 配置文件示例
# 仅包含已实现的后端：macOS 和飞书
#
# 使用说明：
# 1. 复制此文件为 config.toml
# 2. 根据需要修改配置参数
# 3. 填写您的实际飞书机器人配置信息
# 4. config.toml 文件已被 .gitignore 忽略，不会被提交到版本控制

[server]
# 服务器基本配置
name = "Notice MCP Server"
version = "1.0.0"
port = 3000
debug = false

[logging]
# 日志配置
level = "info"  # debug, info, warn, error
file = "logs/notice-mcp.log"
enable_console = true


# MacOS系统通知配置
[backends.macos]
enabled = true
default_sound = "Glass"
default_subtitle = "来自 Notice MCP"
show_in_notification_center = true

# 可用的系统声音列表
[backends.macos.sounds]
available = [
    "Basso", "Blow", "Bottle", "Frog", "Funk",
    "Glass", "Hero", "Morse", "Ping", "Pop",
    "Purr", "Sosumi", "Submarine", "Tink"
]

# 飞书通知配置
[backends.feishu]
enabled = true
webhook_url = "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_WEBHOOK_TOKEN"
# secret = "your-bot-secret"  # 可选，用于安全验证

# Webhook通知配置
[backends.webhook]
enabled = true
default_url = "https://your-webhook-endpoint.com/notify"
default_method = "POST"
timeout = 5000



# 速率限制配置
[rate_limiting]
enabled = true
max_requests_per_minute = 60

# 每个后端的速率限制
[rate_limiting.backends]
macos = 60      # 每分钟最多60个系统通知
feishu = 30     # 每分钟最多30条飞书消息
webhook = 30    # 每分钟最多30个webhook请求